# Generated by Django 4.2.1 on 2023-06-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20230608_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], default='NO', max_length=2, verbose_name='Chip'),
        ),
    ]
