# Generated by Django 4.2.1 on 2023-06-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_mascota_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='NO', max_length=2, verbose_name='Chip'),
        ),
    ]
