# Generated by Django 4.2.1 on 2023-06-12 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_mascota_chip'),
        ('users', '0062_merge_20230611_1612'),
    ]

    operations = [
    ]
