# Generated by Django 4.2.1 on 2023-06-12 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_merge_20230612_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diareserva',
            name='fechaReserva',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Dia'),
        ),
    ]
