# Generated by Django 4.2.2 on 2023-06-13 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0064_alter_diareserva_fechareserva"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calificacion",
            name="rating",
        ),
        migrations.AddField(
            model_name="calificacion",
            name="calificacion",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="calificacion",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Calificacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promediocalificacion",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
