# Generated by Django 4.2.2 on 2023-06-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0065_remove_calificacion_rating_calificacion_calificacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
