# Generated by Django 4.2.1 on 2023-06-13 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_reservacliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacliente',
            name='horaFin',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='horaInicio',
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='idReserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idReserva', to='users.diareserva'),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCuidador', to=settings.AUTH_USER_MODEL),
        ),
    ]
