# Generated by Django 4.2.1 on 2023-06-13 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_delete_reservacliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCliente', to=settings.AUTH_USER_MODEL)),
                ('cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idCuidador', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EstadoReserva', to='users.estadoreserva')),
                ('fechaReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FechaReserva', to='users.diareserva')),
                ('idReserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idReserva', to='users.diareserva')),
            ],
        ),
    ]
