# Generated by Django 4.2.1 on 2023-06-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_reservacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacliente',
            name='cliente',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='idReserva',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
