# Generated by Django 4.2.1 on 2023-06-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_alter_reservacliente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacliente',
            name='idCliente',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='cliente',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='idReserva',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
