# Generated by Django 4.2.1 on 2023-06-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_reservacliente_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacliente',
            name='idCuidador',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='fechaReserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
