# Generated by Django 4.2.1 on 2023-06-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_alter_user_id'),
        ('users', '0073_alter_reservacliente_cuidador'),
    ]

    operations = [
    ]
